[package]
name = "learn__crate__serde"
version = "0.1.0"
authors = ["Max Block <maxblock@pm.me>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
serde_yaml = "0.8"